spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/partydb}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME:party}
    password: ${DB_PASSWORD:party}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
